//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.25 at 01:31:56 AM IST 
//


package com.example.calculator.spring.boot.saop.webservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.calculator.spring.boot.saop.webservic package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.calculator.spring.boot.saop.webservic
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CalculatorRequest }
     * 
     */
    public CalculatorRequest createCalculatorRequest() {
        return new CalculatorRequest();
    }

    /**
     * Create an instance of {@link CalculatorResponse }
     * 
     */
    public CalculatorResponse createCalculatorResponse() {
        return new CalculatorResponse();
    }

    /**
     * Create an instance of {@link CalculatorRequest.NumberArray }
     * 
     */
    public CalculatorRequest.NumberArray createCalculatorRequestNumberArray() {
        return new CalculatorRequest.NumberArray();
    }

}
